image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - cd gcp-infrastructure
  - rm -rf .terraform
  - terraform --version
  - mkdir -p ./creds
  - echo $TERRAFORM_BUCKET_SA | base64 -d > ./creds/serviceaccount.json
  - terraform init

stages:
  - test
  - build

test:
  stage: test

test:
  stage: build