image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - cd gcp-infrastructure
  - rm -rf .terraform
  - terraform --version
  - mkdir -p ./creds
  - echo $TERRAFORM_BUCKET_SA | base64 -d > ./creds/serviceaccount.json
  - export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/creds/serviceaccount.json"
  - terraform init -backend-config="bucket=$TF_VAR_GCP_BUCKET"
  - terraform apply -auto-approve

stages:
  - test
  - build

test:
  stage: test
  script:
    - echo "TEST STAGE"
    - pwd 
    - ls

build:
  stage: build
  script:
    - echo "BUILD STAGE"