variables:
  CI_REGISTRY: eu.gcr.io
  TF_VAR_GCP_BUCKET: terraform-dummy-pdf-or-png
  TF_VAR_GCP_PROJECT_ID: sre-assignment-ermal-kristo

stages:
  - dockerfile_lint
  - test
  - dockerbuild
  - deploy

dockerfile lint:
  stage: dockerfile_lint
  image: hadolint/hadolint:latest-alpine
  before_script:
    - hadolint --version
  script:
    - hadolint dummy-pdf-or-png/Dockerfile
    - hadolint frontend-microservice/Dockerfile

test:
  stage: test
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t frontend-microservice:${CI_COMMIT_SHORT_SHA} ./frontend-microservice/
    - docker run --entrypoint 'sh' frontend-microservice:${CI_COMMIT_SHORT_SHA} -c '/usr/local/bin/npm run test-jest'

docker build:
  stage: dockerbuild
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u _json_key -p "$(echo $TERRAFORM_BUCKET_SA | base64 -d)" https://${CI_REGISTRY}
    - docker info
  script:
    - docker build -t ${CI_REGISTRY}/${TF_VAR_GCP_PROJECT_ID}/frontend-microservice:${CI_COMMIT_SHORT_SHA} ./frontend-microservice/
    - docker tag ${CI_REGISTRY}/${TF_VAR_GCP_PROJECT_ID}/frontend-microservice:${CI_COMMIT_SHORT_SHA} ${CI_REGISTRY}/${TF_VAR_GCP_PROJECT_ID}/frontend-microservice:latest
    - docker push ${CI_REGISTRY}/${TF_VAR_GCP_PROJECT_ID}/frontend-microservice:${CI_COMMIT_SHORT_SHA}
    - docker push ${CI_REGISTRY}/${TF_VAR_GCP_PROJECT_ID}/frontend-microservice:latest
    - docker build -t ${CI_REGISTRY}/${TF_VAR_GCP_PROJECT_ID}/dummy-pdf-or-png:${CI_COMMIT_SHORT_SHA} ./dummy-pdf-or-png/
    - docker tag ${CI_REGISTRY}/${TF_VAR_GCP_PROJECT_ID}/dummy-pdf-or-png:${CI_COMMIT_SHORT_SHA} ${CI_REGISTRY}/${TF_VAR_GCP_PROJECT_ID}/dummy-pdf-or-png:latest
    - docker push ${CI_REGISTRY}/${TF_VAR_GCP_PROJECT_ID}/dummy-pdf-or-png:${CI_COMMIT_SHORT_SHA}
    - docker push ${CI_REGISTRY}/${TF_VAR_GCP_PROJECT_ID}/dummy-pdf-or-png:latest
  after_script:
    - docker logout ${CI_REGISTRY}



deploy:
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script:
    - cd gcp-infrastructure
    - rm -rf .terraform
    - terraform --version
    # - mkdir -p ./creds
    # - echo $TERRAFORM_BUCKET_SA | base64 -d > ./creds/serviceaccount.json
    # - export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/creds/serviceaccount.json"
    # - terraform init -backend-config="bucket=$TF_VAR_GCP_BUCKET"
    # - terraform apply -auto-approve
  script:
    - echo "DEPLOY STAGE"
    - pwd 
    - ls