apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: frontend-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 9000
    type: HTTP
    requestPath: /health