apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-deployment
  name: frontend-deployment
spec:
  template:
    spec:
      containers:
      - name: frontend-app
        env:
          - name: NODE_ENV
            value: development
          - name: BACKEND_URL
            value: http://backend-service.$(NAMESPACE).svc