apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-dummy-pdf-png
resources:
- namespace.yaml
- ../../bases
patchesStrategicMerge:
- frontend-deployment.yaml
commonLabels:
  app: dummy-pdf-png
vars:
- fieldref: {}
  name: NAMESPACE
  objref:
    apiVersion: v1
    kind: Namespace
    name: dev-dummy-pdf-png
images:
- name: FRONTEND-APP
  newName: //frontend-microservice
  newTag: "123456"

secretGenerator:
- files:
  - secrets/.dockerconfigjson
  name: gcr-json-key
  type: kubernetes.io/dockerconfigjson